services:
  - type: web
    name: pdf-to-audio-api
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MINIMAX_API_KEY
        sync: false
      - key: MINIMAX_GROUP_ID
        sync: false
      - key: DEBUG
        value: False
      - key: LOG_LEVEL
        value: INFO
    autoDeploy: false
